/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-24 04:30:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Start Footer -->\r\n");
      out.write("<footer class=\"bg-dark\" id=\"tempaltemo_footer\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-md-4 pt-5\">\r\n");
      out.write("        <h2 class=\"h2 text-success border-bottom pb-3 border-light logo\">VARAN Designs Shop</h2>\r\n");
      out.write("        <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <i class=\"fas fa-map-marker-alt fa-fw\"></i>\r\n");
      out.write("            123 Consectetur at ligula 10660\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <i class=\"fa fa-phone fa-fw\"></i>\r\n");
      out.write("            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">010-020-0340</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <i class=\"fa fa-envelope fa-fw\"></i>\r\n");
      out.write("            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">varanDesigns@gmail.com</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-md-4 pt-5\">\r\n");
      out.write("        <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Designs</h2>\r\n");
      out.write("        <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">3D Modals</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">3D Artworks</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Vectors</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Object Animation</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Lines</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Color codings</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\"></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-md-4 pt-5\">\r\n");
      out.write("        <h2 class=\"h2 text-light border-bottom pb-3 border-light\">Further Info</h2>\r\n");
      out.write("        <ul class=\"list-unstyled text-light footer-link-list\">\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Home</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">About Us</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Shop Locations</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">FAQs</a></li>\r\n");
      out.write("          <li><a class=\"text-decoration-none\" href=\"#\">Contact</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row text-light mb-4\">\r\n");
      out.write("      <div class=\"col-12 mb-3\">\r\n");
      out.write("        <div class=\"w-100 my-3 border-top border-light\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-auto me-auto\">\r\n");
      out.write("        <ul class=\"list-inline text-left footer-icons\">\r\n");
      out.write("          <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"http://facebook.com/\"><i class=\"fab fa-facebook-f fa-lg fa-fw\"></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.instagram.com/\"><i class=\"fab fa-instagram fa-lg fa-fw\"></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://twitter.com/\"><i class=\"fab fa-twitter fa-lg fa-fw\"></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"list-inline-item border border-light rounded-circle text-center\">\r\n");
      out.write("            <a class=\"text-light text-decoration-none\" target=\"_blank\" href=\"https://www.linkedin.com/\"><i class=\"fab fa-linkedin fa-lg fa-fw\"></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-auto\">\r\n");
      out.write("        <label class=\"sr-only\" for=\"subscribeEmail\">Email address</label>\r\n");
      out.write("        <div class=\"input-group mb-2\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control bg-dark border-light\" id=\"subscribeEmail\" placeholder=\"Email address\">\r\n");
      out.write("          <div class=\"input-group-text btn-success text-light\">Subscribe</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w-100 bg-black py-3\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row pt-2\">\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("          <p class=\"text-left text-light\">\r\n");
      out.write("            Copyright &copy; 2021 VARAN Designs\r\n");
      out.write("            | Designed by <a rel=\"sponsored\" href=\"https://templatemo.com\" target=\"_blank\">TemplateMo</a>\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- End Footer -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
