/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-11 06:46:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Asus/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244272159L));
    _jspx_dependants.put("jar:file:/C:/Users/Asus/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/home.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("main");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/home.jsp(3,2) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("headBody");
      // /WEB-INF/views/frontend/home.jsp(3,2) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/home.jsp(6,2) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("homeBody");
      // /WEB-INF/views/frontend/home.jsp(6,2) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setType("REPLACE");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    <title>VARAN Designs</title>\r\n");
      out.write("  ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal -->\r\n");
      out.write("    <div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("        <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("          <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("          <div class=\"input-group mb-2\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("            <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("              <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Banner Hero -->\r\n");
      out.write("    <div id=\"template-mo-zay-hero-carousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("      <ol class=\"carousel-indicators\">\r\n");
      out.write("        <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("        <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("        <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("      </ol>\r\n");
      out.write("      <div class=\"carousel-inner\">\r\n");
      out.write("        <div class=\"carousel-item active\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row p-5\">\r\n");
      out.write("              <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"./assets/img/banner_img_01.jpg\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                <div class=\"text-align-left align-self-center\">\r\n");
      out.write("                  <h1 class=\"h1 text-success\"><b>VARAN Designs</b> Company</h1>\r\n");
      out.write("                  <h3 class=\"h2\">Perfect Quality</h3>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    VARAN Designs Shop is an latest version of design Marketing.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row p-5\">\r\n");
      out.write("              <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"./assets/img/banner_img_02.gif\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                <div class=\"text-align-left\">\r\n");
      out.write("                  <h1 class=\"h1\">Most Priority</h1>\r\n");
      out.write("                  <h3 class=\"h2\">High-Standard</h3>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    To Develop Our Designs to worldwide stream.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row p-5\">\r\n");
      out.write("              <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"./assets/img/banner_img_03.jpg\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                <div class=\"text-align-left\">\r\n");
      out.write("                  <h1 class=\"h1\">To Display Live experience in screen</h1>\r\n");
      out.write("                  <h3 class=\"h2\">Not only a object.</h3>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    This is the technology that we need.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a class=\"carousel-control-prev text-decoration-none w-auto ps-3\" href=\"#template-mo-zay-hero-carousel\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("        <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"carousel-control-next text-decoration-none w-auto pe-3\" href=\"#template-mo-zay-hero-carousel\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("        <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Banner Hero -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Categories of The Month -->\r\n");
      out.write("    <section class=\"container py-5\">\r\n");
      out.write("      <div class=\"row text-center pt-3\">\r\n");
      out.write("        <div class=\"col-lg-6 m-auto\">\r\n");
      out.write("          <h1 class=\"h1\">Categories of The Month</h1>\r\n");
      out.write("          <p>\r\n");
      out.write("            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia\r\n");
      out.write("            deserunt mollit anim id est laborum.\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("          <a href=\"#\"><img src=\"./assets/img/category_img_01.jpg\" class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("          <h5 class=\"text-center mt-3 mb-3\">3D Artworks</h5>\r\n");
      out.write("          <p class=\"text-center\"><a class=\"btn btn-success\" href=\"shop\">Go Shop</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("          <a href=\"#\"><img src=\"./assets/img/category_img_02.jpg\" class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("          <h2 class=\"h5 text-center mt-3 mb-3\">Vectors</h2>\r\n");
      out.write("          <p class=\"text-center\"><a class=\"btn btn-success\" href=\"shop\">Go Shop</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-12 col-md-4 p-5 mt-3\">\r\n");
      out.write("          <a href=\"#\"><img src=\"./assets/img/category_img_03.gif\" class=\"rounded-circle img-fluid border\"></a>\r\n");
      out.write("          <h2 class=\"h5 text-center mt-3 mb-3\">Animations</h2>\r\n");
      out.write("          <p class=\"text-center\"><a class=\"btn btn-success\" href=\"shop\">Go Shop</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End Categories of The Month -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Featured Product -->\r\n");
      out.write("    <section class=\"bg-light\">\r\n");
      out.write("      <div class=\"container py-5\">\r\n");
      out.write("        <div class=\"row text-center py-3\">\r\n");
      out.write("          <div class=\"col-lg-6 m-auto\">\r\n");
      out.write("            <h1 class=\"h1\">Featured Designs</h1>\r\n");
      out.write("            <p>\r\n");
      out.write("              Reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\r\n");
      out.write("              Excepteur sint occaecat cupidatat non proident.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card h-100\">\r\n");
      out.write("              <a href=\"shop-single.html\">\r\n");
      out.write("                <img src=\"./assets/img/feature_prod_01.gif\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"text-muted text-right\">$240.00</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"shop-single.html\" class=\"h2 text-decoration-none text-dark\">Drawings</a>\r\n");
      out.write("                <p class=\"card-text\">\r\n");
      out.write("                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt in culpa qui officia deserunt.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"text-muted\">Reviews (24)</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card h-100\">\r\n");
      out.write("              <a href=\"shop-single.html\">\r\n");
      out.write("                <img src=\"./assets/img/feature_prod_02.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"text-muted text-right\">$480.00</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"shop-single.html\" class=\"h2 text-decoration-none text-dark\">Cloud DesignDTO works</a>\r\n");
      out.write("                <p class=\"card-text\">\r\n");
      out.write("                  Aenean gravida dignissim finibus. Nullam ipsum diam, posuere vitae pharetra sed, commodo ullamcorper.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"text-muted\">Reviews (48)</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-12 col-md-4 mb-4\">\r\n");
      out.write("            <div class=\"card h-100\">\r\n");
      out.write("              <a href=\"shop-single.html\">\r\n");
      out.write("                <img src=\"./assets/img/feature_prod_03.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <ul class=\"list-unstyled d-flex justify-content-between\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                    <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"text-muted text-right\">$360.00</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"shop-single.html\" class=\"h2 text-decoration-none text-dark\">Artworks</a>\r\n");
      out.write("                <p class=\"card-text\">\r\n");
      out.write("                  Curabitur ac mi sit amet diam luctus porta. Phasellus pulvinar sagittis diam, et scelerisque ipsum lobortis nec.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"text-muted\">Reviews (74)</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End Featured Product -->\r\n");
      out.write("  ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
