/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-11 06:34:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/Asus/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244272159L));
    _jspx_dependants.put("jar:file:/C:/Users/Asus/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/shop.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("main");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/shop.jsp(3,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("headBody");
      // /WEB-INF/views/frontend/shop.jsp(3,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f1 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f1);
    try {
      _jspx_th_layout_005fput_005f1.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/shop.jsp(6,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setBlock("homeBody");
      // /WEB-INF/views/frontend/shop.jsp(6,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f1.setType("REPLACE");
      _jspx_th_layout_005fput_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_layout_005fput_005f1, null));
      _jspx_th_layout_005fput_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <title>VARAN Designs - Designs Listing Page</title>\r\n");
      out.write("    ");
      return false;
    }
    public boolean invoke2( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <!-- Modal -->\r\n");
      out.write("        <div class=\"modal fade bg-white\" id=\"templatemo_search\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("                <div class=\"w-100 pt-1 mb-5 text-right\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"\" method=\"get\" class=\"modal-content modal-body border-0 p-0\">\r\n");
      out.write("                    <div class=\"input-group mb-2\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputModalSearch\" name=\"q\" placeholder=\"Search ...\">\r\n");
      out.write("                        <button type=\"submit\" class=\"input-group-text bg-success text-light\">\r\n");
      out.write("                            <i class=\"fa fa-fw fa-search text-white\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Start Content -->\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <h1 class=\"h2 pb-4\">Categories</h1>\r\n");
      out.write("                    <ul class=\"list-unstyled templatemo-accordion\">\r\n");
      out.write("                        <li class=\"pb-3\">\r\n");
      out.write("                            <a class=\"collapsed d-flex justify-content-between h3 text-decoration-none\" href=\"#\">\r\n");
      out.write("                                Designs 3D\r\n");
      out.write("                                <i class=\"fa fa-fw fa-chevron-circle-down mt-1\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"collapse show list-unstyled pl-3\">\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">3D Modal</a></li>\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">3D Artworks</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"pb-3\">\r\n");
      out.write("                            <a class=\"collapsed d-flex justify-content-between h3 text-decoration-none\" href=\"#\">\r\n");
      out.write("                                Sale\r\n");
      out.write("                                <i class=\"pull-right fa fa-fw fa-chevron-circle-down mt-1\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul id=\"collapseTwo\" class=\"collapse list-unstyled pl-3\">\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">Color Codes</a></li>\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">Vectors</a></li>\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">Lines</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"pb-3\">\r\n");
      out.write("                            <a class=\"collapsed d-flex justify-content-between h3 text-decoration-none\" href=\"#\">\r\n");
      out.write("                                Designs\r\n");
      out.write("                                <i class=\"pull-right fa fa-fw fa-chevron-circle-down mt-1\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul id=\"collapseThree\" class=\"collapse list-unstyled pl-3\">\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">Arts</a></li>\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">Structures</a></li>\r\n");
      out.write("                                <li><a class=\"text-decoration-none\" href=\"#\">2D Charactors</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-9\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <ul class=\"list-inline shop-top-menu pb-3 pt-1\">\r\n");
      out.write("                                <li class=\"list-inline-item\">\r\n");
      out.write("                                    <a class=\"h3 text-dark text-decoration-none mr-3\" href=\"#\">All</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item\">\r\n");
      out.write("                                    <a class=\"h3 text-dark text-decoration-none mr-3\" href=\"#\">3D</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"list-inline-item\">\r\n");
      out.write("                                    <a class=\"h3 text-dark text-decoration-none\" href=\"#\">2D</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 pb-4\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <select class=\"form-control\">\r\n");
      out.write("                                    <option>Featured</option>\r\n");
      out.write("                                    <option>A to Z</option>\r\n");
      out.write("                                    <option>DesignDTO</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_08.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_03.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_05.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_07.jpeg\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_02.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_06.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_04.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_01.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <div class=\"card mb-4 product-wap rounded-0\">\r\n");
      out.write("                                <div class=\"card rounded-0\">\r\n");
      out.write("                                    <img class=\"card-img rounded-0 img-fluid\" src=\"assets/img/shop_09.png\">\r\n");
      out.write("                                    <div class=\"card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <ul class=\"list-unstyled\">\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white\" href=\"shop-single.html\"><i class=\"far fa-heart\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"far fa-eye\"></i></a></li>\r\n");
      out.write("                                            <li><a class=\"btn btn-success text-white mt-2\" href=\"shop-single.html\"><i class=\"fas fa-cart-plus\"></i></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <a href=\"shop-single.html\" class=\"h3 text-decoration-none\">Oupidatat non</a>\r\n");
      out.write("                                    <ul class=\"w-100 list-unstyled d-flex justify-content-between mb-0\">\r\n");
      out.write("                                        <li>M/L/X/XL</li>\r\n");
      out.write("                                        <li class=\"pt-2\">\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-red float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-blue float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-black float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-light float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                            <span class=\"product-color-dot color-dot-green float-left rounded-circle ml-1\"></span>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <ul class=\"list-unstyled d-flex justify-content-center mb-1\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-warning fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"text-muted fa fa-star\"></i>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p class=\"text-center mb-0\">$250.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div div=\"row\">\r\n");
      out.write("                        <ul class=\"pagination pagination-lg justify-content-end\">\r\n");
      out.write("                            <li class=\"page-item disabled\">\r\n");
      out.write("                                <a class=\"page-link active rounded-0 mr-3 shadow-sm border-top-0 border-left-0\" href=\"#\" tabindex=\"-1\">1</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item\">\r\n");
      out.write("                                <a class=\"page-link rounded-0 mr-3 shadow-sm border-top-0 border-left-0 text-dark\" href=\"#\">2</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"page-item\">\r\n");
      out.write("                                <a class=\"page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark\" href=\"#\">3</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Content -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start Brands -->\r\n");
      out.write("        <section class=\"bg-light py-5\">\r\n");
      out.write("            <div class=\"container my-4\">\r\n");
      out.write("                <div class=\"row text-center py-3\">\r\n");
      out.write("                    <div class=\"col-lg-6 m-auto\">\r\n");
      out.write("                        <h1 class=\"h1\">Our Brands</h1>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("                            Lorem ipsum dolor sit amet.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-9 m-auto tempaltemo-carousel\">\r\n");
      out.write("                        <div class=\"row d-flex flex-row\">\r\n");
      out.write("                            <!--Controls-->\r\n");
      out.write("                            <div class=\"col-1 align-self-center\">\r\n");
      out.write("                                <a class=\"h1\" href=\"#multi-item-example\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("                                    <i class=\"text-light fas fa-chevron-left\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--End Controls-->\r\n");
      out.write("\r\n");
      out.write("                            <!--Carousel Wrapper-->\r\n");
      out.write("                            <div class=\"col\">\r\n");
      out.write("                                <div class=\"carousel slide carousel-multi-item pt-2 pt-md-0\" id=\"multi-item-example\" data-bs-ride=\"carousel\">\r\n");
      out.write("                                    <!--Slides-->\r\n");
      out.write("                                    <div class=\"carousel-inner product-links-wap\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("                                        <!--First slide-->\r\n");
      out.write("                                        <div class=\"carousel-item active\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_01.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_02.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_03.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_04.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!--End First slide-->\r\n");
      out.write("\r\n");
      out.write("                                        <!--Second slide-->\r\n");
      out.write("                                        <div class=\"carousel-item\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_01.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_02.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_03.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_04.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!--End Second slide-->\r\n");
      out.write("\r\n");
      out.write("                                        <!--Third slide-->\r\n");
      out.write("                                        <div class=\"carousel-item\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_01.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_02.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_03.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-3 p-md-5\">\r\n");
      out.write("                                                    <a href=\"#\"><img class=\"img-fluid brand-img\" src=\"assets/img/brand_04.png\" alt=\"Brand Logo\"></a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!--End Third slide-->\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!--End Slides-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--End Carousel Wrapper-->\r\n");
      out.write("\r\n");
      out.write("                            <!--Controls-->\r\n");
      out.write("                            <div class=\"col-1 align-self-center\">\r\n");
      out.write("                                <a class=\"h1\" href=\"#multi-item-example\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("                                    <i class=\"text-light fas fa-chevron-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--End Controls-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--End Brands-->\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
